[project]
name = "safespace-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "sankhadeep.genx@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "streamlit>=1.63.0",
]

[project.scripts]
safespace-ai = "safespace_ai:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
